language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tcesario/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tcesario/react-test npm test -- --coverage

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t tcesario/multi-client ./client
  - docker build -t tcesario/multi-nginx ./nginx
  - docker build -t tcesario/multi-server ./server
  - docker build -t tcesario/multi-worker ./worker
  - docker push tcesario/multi-client
  - docker push tcesario/multi-nginx
  - docker push tcesario/multi-server
  - docker push tcesario/multi-work
